# Generated by Django 5.2.7 on 2025-10-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_premium_user_user_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_generations',
            field=models.IntegerField(default=0),
        ),
    ]
