# Generated by Django 5.2.7 on 2025-10-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_user_number_of_generations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
