# Generated by Django 5.2.7 on 2026-02-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_userfingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_credits',
            field=models.IntegerField(default=0),
        ),
    ]
