# Generated by Django 5.2.7 on 2025-10-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pricing_duration', models.CharField(choices=[('Month', 'Month'), ('Year', 'Year')], max_length=250)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('lengthy_summaries', models.BooleanField(default=False)),
                ('lengthy_qa', models.BooleanField(default=False)),
                ('audio_summary', models.BooleanField(default=True)),
                ('number_of_generations', models.IntegerField(default=0)),
            ],
        ),
    ]
