# Generated by Django 5.2.7 on 2025-10-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
