# Generated by Django 5.2.7 on 2025-10-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0002_pricing_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='pricing_duration',
            field=models.CharField(choices=[('Month', 'Month'), ('Year', 'Year'), ('Free', 'Free')], max_length=250),
        ),
    ]
