# Generated by Django 5.2.7 on 2025-10-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0003_alter_pricing_pricing_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='number_of_generations',
        ),
    ]
