# Generated by Django 5.2.7 on 2025-11-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pricing',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
