# Generated by Django 5.2.7 on 2026-02-01 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_add_unique_reference'),
        ('payment', '0002_remove_transaction_pricing_and_more'),
    ]

    operations = [
    ]
