# Generated by Django 5.2.7 on 2025-10-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time_taken',
        ),
    ]
