# Generated by Django 5.2.7 on 2025-11-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_alter_quiz_options_remove_userattempt_time_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
