# Generated by Django 5.2.7 on 2025-10-16 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=50)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_for_log_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
