# Generated by Django 5.2.7 on 2025-10-10 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('used_past_questions', models.BooleanField(default=False)),
                ('past_questions_context', models.TextField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('questions_answers', models.JSONField(default=dict)),
                ('audio_summary', models.FileField(blank=True, null=True, upload_to='audio_summaries/')),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='pdf_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'processing_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
