# Generated by Django 5.2.7 on 2025-10-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socratic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='quiz_generated',
            field=models.BooleanField(default=False),
        ),
    ]
