# Generated by Django 5.2.7 on 2025-10-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socratic', '0002_processingresult_quiz_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='status',
            field=models.CharField(default='PROCESSING', max_length=50),
        ),
    ]
