# Generated by Django 5.2.7 on 2025-10-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socratic', '0003_processingresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='audio_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='pdf_generated',
            field=models.BooleanField(default=False),
        ),
    ]
