# Generated by Django 5.2.7 on 2025-11-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socratic', '0004_processingresult_audio_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingresult',
            name='audio_summary',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
