# Generated by Django 5.2.7 on 2026-01-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socratic', '0005_alter_processingresult_audio_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='processing_stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('extracting_text', 'Extracting Text'), ('generating_summary', 'Generating Summary'), ('creating_pdf', 'Creating PDF'), ('generating_audio', 'Generating Audio'), ('creating_quiz', 'Creating Quiz'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='stage_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='stage_progress',
            field=models.IntegerField(default=0),
        ),
    ]
