# Generated by Django 5.2.7 on 2026-02-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socratic', '0006_processingresult_processing_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
