# Generated by Django 5.2.7 on 2026-02-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socratic', '0007_processingresult_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='flashcards',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='is_premium_generation',
            field=models.BooleanField(default=False),
        ),
    ]
